{{- if .Values.web.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "app-back.fullname" . }}-web
  labels:
    {{- include "app-back.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  minAvailable: {{ .Values.web.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "app-back.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
{{- end }}
{{- if .Values.worker.pdb.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "app-back.fullname" . }}-worker
  labels:
    {{- include "app-back.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  minAvailable: {{ .Values.worker.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "app-back.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
{{- end }}
