apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-back.fullname" . }}-web
  labels:
    {{- include "app-back.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    {{- include "app-back.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: metrics
      port: 9091
      targetPort: metrics
