---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-pull
  namespace: app-prod
spec:
  encryptedData:
    .dockerconfigjson: AgCOUmVuXgSOV7KT4Rcp8PT8ssvyacjHc3CsneIHoMsp2e/rKyL3sWhaxdlxFbEMleAR2XLir2BltIVpJUc8xUrsCs2gv1OlVga5Ps8M5nqFIreN3jr75yoH/pWBPyr7Qrst14Y5TU4akfnTypFKIO50JIAdMSc8I/G4BFT8DTUTgD9CYEUF8jS7Wb2FgLbYf1TrR2DW1kovXm8u6j3BYyZStbdCmRpbgtQSVArW4ARTFbCsgXrqwrw+zrvAu7A3+XVXT90I1YuTpEZOtEyaKnwDm0FUswC7Fc4ctfR1JKdSSC0igrTMmqjge5hvypIkavEts4zo1NocqUHS55eBZ6lcEZ8G0TCJTZ8WM0+b/LwgpGeChaB+wL1nmdVm+l5G7wil3py1MdwDZDPleRfNLnR/yqowQU2jSIq6WQfVkCPov/ASx9R9/FI3zpCC/izhJRwgNbzkxYhAo0geKis2fPNfv7ym1I0mbF7XccBpgLnBsInrbcvz+mPX/AxVNT4JbsJ2ll4Irr4UPWQbfu+25bKe3tYBi1PL+Cp3sp50thA3CDQzRLR1zNdIdPKGPkZPAtysMxZz1zlDNd2WrcNYG8c5wZHN4WA666Dtx4ZWF29c7Fldul/vJytmfCo6tlHXX6KCJFlRjWSRprn3y3+3Sy7bTWMHPK/mc/Lf/90ToqQeKSNZ3HCbIVLc0rnQlBTTxPXGO4bsNekxo+seUB+QKNaMXyxv77htlrWOWEtAZ+QcK65PwGFDIE1L43wL/cQx6O1leYBKsLBcr6zErGF0bV82lM5KqCE6BYiaGTLwOk1QK3viwzTRk4I4PCBtT8hLIV5/g3P1iyd4o9PS46Bt0u1NiScJbXrKSeG92nnL/C3A/iQPP4lRwFXhyawlIJf3WxzvCJpBSQ==
  template:
    metadata:
      name: registry-pull
      namespace: app-prod
    type: kubernetes.io/dockerconfigjson
