---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-pull
  namespace: app-dev
spec:
  encryptedData:
    .dockerconfigjson: AgB2ORXz+pNlGYBAdXrWDrGgJ4i2+smifE8qRscF5mjdwmiw4hwqT28fh88gUnjsVcxX4qmqU2DqTVmV2AyAclKAnJTUXodVa6iJiDGVwiIsPeFosLuAFZVrjVe3+AewYk6JajIhoUDZ7EYb5nme6BLW8ELHunzwRrh7UPosHPSOUsPpHPTklj1JyEfJIyj85s5xJa81rXra8IGXknOzYb8p82yDlosvyxV9b6/KgpBD5iJAiEzRPi/6wDDmpUFlZr33s2mqH/Cg0fLCCQHTJ35psx4nyulDkInlPUMM6MEcEyTsajW1idw2ue6z2I07fyalOwJFNGmW70LEWewB4WCKEgvI73BaSmSLDlyhEpQQanLyPKV+OZwZ+5xElkVSCsjwdN7xTpkhHEFGPrjHeo5Z1Jwbzfk97GszI/XaetgnNMli431ZKgcChNpvVAo35X8alz724+l+O/ZrADSUAEMQKaA9UOa54Spx4AlOnpC2O6AS7G2+lh91RTJRnIP9yQqk8eO6PPj9YNOI0I17S/dmTYYZn0HXFS9TWrLad26lMOT4RaPsGqE9OsHVFB6Jv1lVHpdOcAPAAKqOrdI0wcil8Rnp8kSUuQmtx1Ue+uURqyEhoH/iHKWwLY/JYMsZOn1gPs5TFflX9V1ETKFAWCHbGZ5Efj93nqRWBBmprHQ/mH3m+837Z6o0IoS/Z7MQ6eE8Zvcyz8Illy0ubZsQWylinmhRPHIoUkVQtrOQSlD79Kiacn8zkhYrnborKHpN9xoyV0IiVMq6EBNtAL+LGhnuhuEKFsdYhVyVJi7cp90uSzjdEd5eMynRDLBNDCSVeNHDnS1dWFU7OIBkKu6M8Cq0g09EFg2+mK8AzTxndo5jq2jtUnncyGJLYrbZ7G04qpdIab9TBA==
  template:
    metadata:
      name: registry-pull
      namespace: app-dev
    type: kubernetes.io/dockerconfigjson
