---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAKaZhuUmTntsPLKUbCJ62OgCMAwQJGVCdyVEz4hxL7oVKYEWOeOggoX/Ty6rfXAb1ENAaERq1OfntAUawEGHWgoledOZ/phTfl9RARxZCsvl58tlRLHw+bo4fLHE2tz5F9YekOm+IUYQl+ecIFqQMMVkLU07OaoZLN4+CSyxgGHUssU93ViCL0lCmCeWyyEFjdjrQWxHBHuFGZTb3aoPIOdCQovcp62xLDIWVmAAGT47/Gth+F0HLkmibiMcRAApVZzpFYojbYiHiOWNxcZCm++N8hxnupSK+T0HX0Z1WvGmrPlW2beTggn11bMp7OcrVvRFQ6y/zwUwdjcwk5NTTjpvDQrhu8aQ90cFBD+cS7QBjSLX0ODV0qxpXRf5mVWKSSXlO4eZ8s4dPu4oWANHqaqao2kJ3DZ58cBHQ7bCu/aOT+rsVXKWcS10WP8g5cdV6Oxx/Ajas4Z7frm2LguJ7mer6bp9VXAD0BDxs8V9/Owjvr6rw5zDdgbw03D9z5NBH2W1/9UVUia9QRfvk+1PC+Au56mVnbex7hZMJCqkv44IaHX8KzDQL2i/qvDTthebp9fhkQPH/dR3OubYdI+oqYO0aArkMPWmoI0B9h06ZOyWmSF05LrHy/yRdcsAAKL4ALIKrem/e4+kLvHeRS4DtoXpfNC9bSwGRHVJr+nQGChrPpTB+emLAyZr4hVf3M2eJF2mPCTNI=
    admin-user: AgARcQxH9f90KZlhibfw3VHBwm8TdCdObnrQjimDgaQPnZulGnKc6RJevDgHwP25Y3iYobHxUFP1Sp/zv91wMvQD8YsIJ9L35qF8ezgRkN61RLkvL2v63rPrU3cD9R0cVZXessbhT9Mau36lrF3YmsMl9I4FSI6WsdSrAhYV6idIZZRNMUNALq+GurFfJWTp2Bq2swDKTXTBJPLn+62Ni3jVkfcU2NzQKtzRQF+ztPy1/XhIxck62kW3oTP7qvlsIWV2sfAIFXNN8QJcT1sNlrU0rK9lwwl997VsbxBPXKLxttdxd/t5arV9FrRz8WjjLuO3JyyomGqIImFpJRP3t1sXNmwSaytwo6ooIEwWRZq2K00A9dSTNUXHgwMbaQi75Z4HM1Tb7jZgLqUxwm592bwoGwoxLm+1MB9a08bFj6nWn1b1VwJQfG9CpvIFIcPU7XL5kRlq+uAwbh3B9aPwFiXMthH6yJc2V0osYay75FthX5Ovi4a/BUsrcULmSfCZyJk+1MTDIzrcma0vlzxWchFeDnwtXc23rXavoec8vTfp2gCRIuBMPVZ9Z71Nn1SWEjfs+QUtILkd1BgvepegTuc5IFY7APK6E4KWJCnJivhyi/0V2m87iEVmK2qPPxArioA1j6VE01DREjfwfuaI4RpatfnPn+vakLDKKw5shoKAVzqGoyvb/AF3/2KitZHfu9ZdcI7x9A==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
