---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: redis
spec:
  encryptedData:
    redis-extra.conf: AgApNtHbaYYeQo8C4u4ubeLvuTrixgko7mdFWf+1i6SKaxR7ldDG2BA9GWjQi9lqlYg8HDlxGe8bMoR9yz+aQikYtCjX0t/jyESfHcR/eyqpD0y1oR2/1x0aW8VhknEjnDHH2wUegM2OuBQn/jzA3nXGkpgzF4BL11LMNzeEhBb11wwY3v8m3iM45TXRxdncK3Ia6lEWynHUgwjsGiclJlBa2NwqH4fUebNYklJy7r/1qmXfHLjNfWzemRBe+S/errnaIfB/ISf9oVX8KkFK3K0dll1ec8g2qmf/FIr0QD9JWalUbttkwhauKbM/zOB0bmi5RuYRwFcEWwl3bNtwuTVji02cjHi7gWLuoLy3dnLD/j5TZ+eiE3HLqcg2Uw7hrs98/a9kQ2ssZnjlvbjZ/Lf83zFRs4M+JMEUmgDUeekDP3YycfGH1NH6sxRxKD8MZVOvdtaT6766662Tf8POIXTSTvWcHO7Uhlvibf0SFadZjIjz7bydqaq4p0MTRgjsK2cfqOOZf86zj6AZ6SF1pUV7NPc8I63gVECdKmQnxcN+buPa++ETf0V2SUoL4Lj1P2IYwep+2psGjBDrarPZPNmDRIUAHWHtXwVjeuowURypM8UKQccblqQ8a/Qi1mguZkcBtC1O/5ja9URkZrj3NoCVqpQiLxtSLw4b+7bSvc83qsbhaZi1tf8F3o7iSGYw66vN72GkeT2mcq27/FVGPviGly6J
  template:
    metadata:
      name: redis-auth
      namespace: redis
    type: Opaque
