---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-htpasswd
  namespace: registry
spec:
  encryptedData:
    htpasswd: AgCtQQN4dXSIWThO1pmpKEHuDMX9bfQz6xJGr5nrytvV+Cu7ZmTDlHz7nsQcBQbcNonm3gFTgoZedA7eX3KelAU8qXTJaSnqOFb9T+NhnRlSbC0nQN/xlfla11TfT3JuY9PhZITHN5zQ04QhSwPdJvGc5J6z0jcUnZS5A6uqvleqEr091KJ5P4QCIYi/TUxhdzlNg0q5t1UhWkhBShyQesA1kUNRRf2aV2Tp7b9YSSVZZpjY6+F1+H0A/G/rhmRAO2pVYS4TXSdP0Hxlxpk+6PmPWpkaJkLQ/C0r7StYW/PJe9ZM+K41esyPUGLENrnh52VyPn4hqScszGwNerQXFxSJqgWWbReQmnigdpeDv5vUSIc1AHvAezYlkiJVurpFR9dolcm4bX0CeMtKSIr7xNThF7FX4Y4hPL60k6YHRFhvoEPncxg0jzK3snF6oyAdBsorD1tN7kA+mWQ0ngI82TeIjjhASFV6ByUG6DRdDcbz5YVSK2F+53IhJqZeT0yislts+1GFMo2wapZ9ttRf2i4zZ1aKL2GMMOgW7sddwjcZY8pQdru+vDJWk+DPS2ZlV/ipsT7HOOnLzAkW4kLj2Ou1RcicTZ9c/TOTvtDdzGxmbtHP2mYWD+CxJgnGi+OuGW4jbk74B5JLSEVPV1JXMMj7ee7vp5T4bJgYvFZo8qznHLw/UetlMtPr49D8F3FfN4RJgP4B3i1pBciKWwyJW5lXfc9oZOmt9OotBOmlUmwYK1eVMmHWzjTpAYmrbWzMUmpJDZEWxgTsL4C1WrFPuKw=
  template:
    metadata:
      name: registry-htpasswd
      namespace: registry
    type: Opaque
