---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-s3
  namespace: registry
spec:
  encryptedData:
    accessKey: AgBOfXHeG3USug+DUDPFXX5A6ruajiBOuu0iTxg5GCuVsSQxbYUJICl+pULVKQXa3Ltyd/TL0baRnQ8W1N3iw47Mhnr741iDKJLWXuTAjU96XMv3ccy5yROilr0pvnnxiGZePrYYw6fk+ki/z9qLDI0IBzEoNAq919YSVQkMLrm6P/Gt4V4XV7TQcZK2u2XjPEh/lJqHILBYZ5EuvCIvUNjd1FR+XBovlxHV1LtGaDxlGb78wAQMAsPHn2ffljhLIkepmkldN8fg7eqN1wT60b8JpaFq1NxOEmu7bbzZk/6JHCQ+5R+Qb5HsNZCNcXe7qDHXZw7SWTNfn2VND35+tGIX65IAZWXM4BWFdeS7VlnK9eiWF+zAvzClaWRSFb9huFkuvh8mXNX02667pIVJ2zwYXIVYCvP9zSQlyIqYL/tENKLJxqW9Ob+Xj/wK1qIPNPHoUhuZ47GE71o6CfWJaG2A08qEaW0TdkJE11ffiDAwc6XFv1WbzdBz+AjqABVATNsiysiZs/KNnktxvcTmUWrvpsuhVclKbnJwGxlpgFfnXt6IAI+tKdwQ9PUTr+z+ehVhe9bngAdXS5JL9jlSIHhMZ+SlBegbJuz0jSL6lu48SIIW4Az16E6giopN2ioLiiS8TJSd7zs/6VSN7LcOYNY5WLv+SNpES880jKyr1Hgqwxm5g5TiZXg+YG7g91IFvNtYlSe5COku4lINug==
    secretKey: AgAwnF2UxOS29SUNFEjsuvTlsup9fRRu5WQwyyej5o2KOq4XAHQvN+CpEH7ne7pjaHVIYXnlw8FEJHahiStKbdEywuEEwoNMX35u7CblzcpHUZRZTsPJIuSMKxCkQZB9QllyW+1y2LLi6h+9tiMTenotI+7EYsAxURU4Ec4bqBiTitaQgpoKjSRZ+mIBg/BoVhiRCQRWuHEG4sdTUhDVkgEMR3MqsY7Xm4BMjNEHW84Jg+hwrKH66QRE/QMQ2wBfjeBsUhKhV9Y0doVIi3nMuWoYu1VMFN5Ta5EElkJ/y3FKzUb6ou1P+ptodXl40hR06qrNOEuKYbv9/Z0xZuiXEj2LmS/plctGySgo3hhPKtx3jmWrWVUIGyTIWeG97/tb0OzPKStrIOq3pFEaoG8kb9x5SbDTyqbfRBNMCpye1236/soK7GK/Q/6Q8eY273ABxTg3ze4YRPjefixhI6m4PnEMCejHe+Y90TCeov5V5PMoQJ5Yo9zCn/9uYatqiWRaRi0CaEUBq1LNrrV44g71/8Dvj0xZ5Sw+wtljB47xT7IgeRs5+s/CfDccVtQfWQbOwMO6gsumURCDFEoIiXGaQkuLxKbycKBFc6VOrteM9q4A5RfiwTjjOTNQ0dvEewOorQ0NHv6bjQePmU7DXJb7gqupGyvhKBKZXPghBon+Og5zYeKesm1voZLoQQn+yYkeAFkIb0xwIplg6Xzqtg==
  template:
    metadata:
      name: registry-s3
      namespace: registry
    type: Opaque
