---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: seaweedfs-s3-admin
  namespace: seaweedfs
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBNvJzkLN3Tw4zDBpucOsWuu6LnMNYv8LqZ74z9F758uX1sLYIBaszGdgaYOa5l2t+w7Ks7KeMOyVt6nzawSMa8uVMrnoLkmuc1MIbYDjZXQbNzpn5U/dSoRexOTgNpwOnrQBYb2OBoqxSLMSRW/m3A6BGU4dzwIlMIyhh95ccl17TQaLzgB/XhtTZ8EuoNuM6awcxtn1EUSNP50vL4wNmq8A//oJajlOR4+4oGyQrcbU7b7zBO85a8KMwrQl12rUL8nR5L6LYilwlvSKU4zl1BWlhMLlUg6h2MNPYWK5X5aRhpLhqHnb2AoiDSZm3kRsXntIv/lXqH94b5MEjl9qnKngMxIqLH8PYEE8Yf2zsNhUTeNQJHnh7Q0qA3C4t3X+xIuYTbbaBIwLyoeqm4aXyuEb7d+3Eu8SZyIYzdFTmP+uQ+QUAG9nHS6cb0P0MsJkaamRhbh3dYJs4+6IQ3NaGu131Uaa27I9mqpzugLfEIRx5DHtR17CFv54PDMZv8sM76NoDWWvu3wS/T0zoa5qkpeSneTwUiUyWRLBfo0cy4Z0lUtuN9TFNgTH8Hq0l6gS9OPkXa//cm5Mo6VVKgYbCgHkxig0+DawHK6jrA+Yi4D1msEINI8OYgb39IamiTo7RWbdNh4ne+i0PZzbVgG+9F09ZIUEHVnVXpCethUH5VZTJVoE2ULwcJMAFwQUe68HAeEqMYx9BqHg==
    AWS_SECRET_ACCESS_KEY: AgCrit1AOi3DoTrgZ5/EKST46iZ9dCgFuOahdZM4iz4y5VHbWOGeJETwcnsrBOYWhxXMlMUdOp4HUdZmu/zucH/kQWPwC25GeXj3EZ1LEhR3YUcaphff+JMhQ9mkuqOwdo6xRg/PhyvBW8uJv1kumIrpqrXVeyD15L+G+tJTU4s0z1GZx5zQbef0G4dzGj9U0pPfBd8/9T1MpuPehtm/5wUVu20/3b3BKOxAMn101XPclE7h/e164YrWYdsFDPnDIlGh+ZNF6AGQhNXRMk4dqmySPUoWqdrjLyOmpwcIuwxGWWKONh8R8iAsRkchh9rnhrjYCvBJ5xnuccUIvkiD/TLmb5cyAvJp0R5705+EAnncidb4wU3LWObUcfkgIPmgkJrw9XRNtp7UgpmP+KALPPHCPomuwKNANiLRdd3ZvBozj5CFBsZ7D6D64CJoof/+EhdBCeOqnZK3x0K5V8g706shONNxlarGjdFWzPGiFX7tk7v3YGEVQqne2ZIRZVyKeEDpzwwIkrcj129cMMF7kmhsn8H436U4FHDEZ/8A4Q/ELyhyi2Cxg3pjSDUakoNGSLLqCMm8niBiFydP0JZ/D+f3qwESVC0r7QIhK4QRrBuZzqodR2bKF92VhKPXlSHWK2+uQIehnGdLDkX6m+5/AKRDVC5GHX0esnSUteDLWmRpUpkIEtEwZPvevGwMAK58Ic8MHo8y7OfUYw==
  template:
    metadata:
      name: seaweedfs-s3-admin
      namespace: seaweedfs
    type: Opaque
